#!/usr/bin/env python3

import sys
import math
import random

def gcd(a, b):
    while b:
        a, b = b, a % b
    return abs(a)

def pollard_rho(n):
    if n % 2 == 0:
        return 2

    x = random.randint(1, n-1)
    y = x
    c = random.randint(1, n-1)
    d = 1
   
    while d == 1:
        x = (x*x + c) % n
        y = (y*y + c) % n
        y = (y*y + c) % n
        d = gcd(x-y, n)
        
        if d == n:
            return pollard_rho(n) 

    return d

def factorize(num):
    factor = pollard_rho(num)
    return factor, num // factor

def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    with open(sys.argv[1], 'r') as file:
        numbers = [int(line.strip()) for line in file]

    for num in numbers:
        p, q = factorize(num)
        print("{}={}*{}".format(num, p, q))

if __name__ == "__main__":
    main()
